# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: v0.7.0
_src_path: gl:znicholls/copier-core-python-repository
conda_release: false
email: zebedee.nicholls@climate-energy-college.org
include_cli: false
name: Zebedee Nicholls
notebook_based_docs: true
package_manager: uv
pandas_doctests: false
plot_dependencies: true
project_description_short: Representation of continuous timeseries.
project_name_human: Continuous Timeseries
project_name_pip: continuous-timeseries
project_name_python: continuous_timeseries
project_url: https://github.com/openscm/continuous-timeseries
track_lock_file: true
